# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SyncTrayzor.SyncTrayzor
PackageVersion: 1.0.6.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/canton7/SyncTrayzor/releases/download/v1.0.8/SyncTrayzorSetup-x64.exe
  InstallerSha256: DCA9D92329D33C7452091F086F539B5851FFB2145AA76FBA35056C6B71B16963
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/canton7/SyncTrayzor/releases/download/v1.0.8/SyncTrayzorSetup-x86.exe
  InstallerSha256: 90E14D49F2A07C45279EFB159D9B86A46D549B5E8D67C4F95364729FEE9A858F
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

