# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SyncTrayzor.SyncTrayzor
PackageVersion: 1.0.6.0
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/canton7/SyncTrayzor/releases/download/v1.0.6/SyncTrayzorSetup-x64.exe
  InstallerSha256: 26228B6CCF16E30B57080024A60DC69CBD6CF38F638A2D7C3D6C0F8470A36B71
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/canton7/SyncTrayzor/releases/download/v1.0.6/SyncTrayzorSetup-x86.exe
  InstallerSha256: 9677DA42144A26281970CAC5C5A813E38D76F35BB422F093737499AE5A45D436
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0